name: Branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  ci:
    name: CI
    uses: settlemint/smart-contracts-actions/.github/workflows/solidity.yml@main
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANVIL_TESTS_PRIVATE_KEY: ${{ secrets.ANVIL_TESTS_PRIVATE_KEY }}
      AIKIDO_SECRET_KEY: ${{ secrets.AIKIDO_SECRET_KEY }}
    with:
      docker-image-name: solidity-empty
      runs-on: foundry
